spring.application.name=forohub

# Configuracion base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/foro_hub}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

# JWT secret (puede sobreescribirse con variable de entorno)
api.security.token.secret=${JWT_SECRET:123456789}

server.port=${PORT:8080}

# Hibernate - dejar que Flyway maneje el esquema
spring.jpa.hibernate.ddl-auto=validate

# Cerrar la conexion a la BD antes de convertir el objeto Java a JSON para enviarselo al cliente
spring.jpa.open-in-view=false

# Permite que Swagger UI envie cookies (como refreshToken)
springdoc.swagger-ui.with-credentials=true

# No enviar detalles de errores al cliente (seguridad)
server.error.include-stacktrace=never

# Expone el endpoint /actuator/health para consultar si el backend esta activo (UP/DOWN)
management.endpoints.web.exposure.include=health

# Oculta los detalles internos y solo devuelve el estado basico "status":"UP" - recomendado por seguridad
management.endpoint.health.show-details=never